//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipDataLayer.DbModel
{
    using System;
    using System.Collections.Generic;
     
    public partial class BMKod 
    {
        public int BMKodId { get; set; }
        public string BMKodAciklama { get; set; }
        public string BMKodAdi { get; set; }
        public string BirimId { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
    }
}
