//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipDataLayer.DbModel
{
    using System;
    using System.Collections.Generic;
     
    public partial class Departman 
    {
        public int departmanId { get; set; }
        public string departmanAdi { get; set; }
        public int deptNo { get; set; }
        public string deptTur { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
        public string bmKodAdi { get; set; }
    }
}
