//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipDataLayer.DbModel
{
    using System;
    using System.Collections.Generic;
     
    public partial class EvrakDurum 
    {
        public long EvrakDurumId { get; set; }
        public int EvrakId { get; set; }
        public int KullaniciId { get; set; }
        public System.DateTime Tarih { get; set; }
        public short DurumId { get; set; }
    }
}
