//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipDataLayer.DbModel
{
    using System;
    using System.Collections.Generic;
     
    public partial class EvrakBirim 
    {
        public int EvrakBirimId { get; set; }
        public Nullable<int> EvrakId { get; set; }
        public Nullable<int> BirimId { get; set; }
        public Nullable<System.DateTime> EklemeZamani { get; set; }
        public Nullable<int> Ekleyen { get; set; }
        public Nullable<System.DateTime> DegistirmeZamani { get; set; }
        public Nullable<int> Degistiren { get; set; }
        public Nullable<System.DateTime> SilmeZamani { get; set; }
        public Nullable<int> Silen { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
        public Nullable<int> EvrakEskiId { get; set; }
        public Nullable<int> YerEskiId { get; set; }
        public string FromTabloAdi { get; set; }
    }
}
