//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvrakTakipDataLayer.DbModel
{
    using System;
    using System.Collections.Generic;
     
    public partial class EvrakKullanici 
    {
        public int EvrakKullaniciId { get; set; }
        public int KullaniciId { get; set; }
        public int EvrakId { get; set; }
        public Nullable<System.DateTime> EklemeZamani { get; set; }
        public Nullable<int> Ekleyen { get; set; }
        public Nullable<bool> SilindiMi { get; set; }
        public Nullable<bool> IlettiMi { get; set; }
        public Nullable<byte> BilgilendirildiMi { get; set; }
        public Nullable<long> TempIletimId { get; set; }
        public Nullable<bool> KapandiMi { get; set; }
    }
}
